name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, lint, and test
      run: |
        yarn
        yarn lint
        yarn test --coverage
      env:
        CI: true
    - uses: devmasx/coverage-check-action@v1.1.0
      with:
        type: lcov
        result_path: coverage/lcov.info
        min_coverage: 90
        token: ${{secrets.GITHUB_TOKEN}}
